export const loginSideBarContent = 
    {
        forgetTextEn:'Forget password?',
        forgetTextAr:"نسيت كلمة المرور؟",       
        facebookEn:"facebook",
        facebookAr:'فيس بوك',
        googleEn:"google",
        googleAr:"جوجل",
        loginWithEn:"or Login with",
        loginWithAr:"او سجل ب",
    
    }
export const addressPageContent = 
    {
        step1En:"Address",
        step1Ar:"العنوان",
        step2En:"CheckOut",
        step2Ar:"الدفع",
        step3En:"Complete",
        step3Ar:"مكتمل",
        titleEn:"Address",
        titleAr:"عنوان الشحن",
        btnTextEn: "Add New Address",
        btnTextAr:"اضف عنوان جديد",
        btnText2En: "Proceed To Pay",
        btnText2Ar:"أكمل عمليه الدفع",
        headingEn:"There is no address, add a new address",
        headingAr:"لا يوجد عنوان , أضف عنوان جديد",
        urlEn:'/payment',
        urlAr:'/payment',
    
    }
export const confirmContent = 
    {
        titleEn:"Thanks, Your Order Has Been Confirmed",
        titleAr:"شكرا، لقد تم تأكيد طلبك",        
        orderInfoEn: "Order Number",
        orderInfoAr: "رقم الطلب " ,
        orderNumEn: '6543Ca1588xs2e5',
        orderNumAr: '6543Ca1588xs2e5',
        detailEn:"You Can Follow up You’r Order" ,
        detailAr: "يمكنك متابعه الطلب",
        btnTextEn:"My Orders",
        btnTextAr:"طلباتي",
        btnText2En: "Track",
        btnText2Ar:"تتبع",
        facebookUrlEn:"/",
        facebookUrlAr:"/",   
        instagramUrlEn:"/",
        instagramUrlAr:"/",   
        twitterUrlEn:"/",
        twitterUrlAr:"/",   
        snapUrlEn:"/",
        snapUrlAr:"/",   
        tiktokUrlEn:"/",
        tiktokUrlAr:"/",   
    }

export const addAddressContent ={
    titleEn:"Add Address",
    titleAr:"أضافه عنوان",   
    btnTextEn:"Add Address",
    btnTextAr:"أضافه عنوان",   
    btnText2En:"Choose On Map",
    btnText2Ar:"حدد من جوجل" ,   
    btnText3En:"Back",
    btnText3Ar:"رجوع" ,   
    placeholderEn:"Abdullah Elzayat",
    placeholderAr:"عبدالله الزيات" ,   
    optionEn:"Optional",
    optionAr:"اختياري" ,    
    placeholder2En:"mobile number",
    placeholder2Ar:"رقم الهاتف",
    placeholder3En:"second mobile number",
    placeholder3Ar:"رقم الهاتف",
    placeholder4En:"City",
    placeholder4Ar:"مدينة" ,   
    placeholder5En: "Neighborhood name and street",
    placeholder5Ar: "اسم الحي والشارع",
    placeholder6En: "Special Place",
    placeholder6Ar:"مكان خاص",  
}
export const notificationContent ={
    msgTabEn:"Messages",
    msgTabAr:"الرسائل",
    offerTabEn: "Offers",
    offerTabAr: "العروض" ,
    msgTitleEn: "The message box is empty",
    msgTitleAr:"صندوق الرسائل فارغ",
    msgSubTitleEn:"There are no new messages",
    msgSubTitleAr:"لا توجد رسائل جديدة",
    offerTitleEn: "The Offer box is empty",
    offerTitleAr:" العروض فارغ",
    offerSubTitleEn: "There are no new offers",
    offerSubTitleAr:"لا توجد عروض جديدة",    
}
export const addedShoppingContent={
    titleEn: "the latest products",
    titleAr:"تسوق من احدث المنتجات",
    btnTextEn: "Continue Marketing",
    btnTextAr:"اذهب للتسوق" ,
    btnText2En: "Complete the Order",
    btnText2Ar:"اكمال الطلب" ,
}
export const AddedCheckedCartContent={
    titleEn: " The product has been added to the shopping cart",
    titleAr:"تمت اضافة للسلة بنجاح",
    priceEn: "Total :Price is 125 SAR",
    priceAr:"التكلفة الاجمالية 150 ريال",
}
export const shoppingCartSideBarContent={
    freeShippingEn: " Do you want free shipping to",
    freeShippingAr:"  هل تريد الشحن المجاني إلى ",
    placeNameEn: "Saudi Arabia?",
    placeNameAr:"المملكة العربية السعودية؟"  ,
    freeShipping2En: "Add ",
    freeShipping2Ar:"أضف" ,
    freeShipping3En:"SAR to your cart",
    freeShipping3Ar:"ريال إلى سلة التسوق الخاصة بك",
    yourBagEn:" YOUR BAG",
    yourBagAr:"حقيبتك " ,
    itemEn:"ITEMS",
    itemAr: "عناصر", 
    titleEn: "My Free Gifts",   
    titleAr: "هداياي المجانية" ,   
    title2En:"the latest products",   
    title2Ar:"تسوق من احدث المنتجات", 
    totalPriceEn:"Total: 3 products - 1950 riyals",  
    totalPriceAr:"الإجمالي : 3 منتجات - 1950 ريال",    
    btnTextEn: "Complete the Order",
    btnTextAr:"اكمال الطلب" , 
    urlEn:"/payment",
    urlAr:"/payment",
}
export const emptyShoppingCartContent=
  {
    titleEn: "Your shopping cart is empty",
    titleAr:"سلة التسوق الخاصة بك فارغة!",
    subTitleEn:"Add some products to the cart to complete your order",
    subTitleAr:"أضف بعض المنتجات إلى سلة التسوق لإكمال طلبك",
  }
export const giftCartContent=
  {
    productNameEn:"Baby Don't Cry Shampoo",
    productNameAr:"شامبو الطفل لا تبكي",
    giftTextEn:"Pre-order Gift",
    giftTextAr:"هدية الطلب المسبق" ,
    giftNumberEn: "1",
    giftNumberAr: "1",
  }


export const productArr=[
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
  {
    img: "/images/cart/2.png",
    offerText: "جديد",
    productName: "Intea Children's Shampo",
    prevPrice: "SAR125",
    price: "SAR 95",
    rating: "5",
    discount: "-24%",
    btnText: "أضف للسله",
  },
]